### ISSUE TITLE
[Bug]: On tablets, the video controls don't stay open

### ISSUE THREAD

**Issue by maxwellward** [movie-web/movie-web#257]
### What happened?

When on a (maybe only some?) tablet device, if you open a video and tap to open the media controls, they show for a moment and then go away. If you manage to tap something while they're open, it will work, but it's very finicky.

### What browsers are you seeing the problem on?

Chrome, Chromium

### Steps to reproduce?

1. Use a tablet device (iPad) and open a video
2. Tap anywhere on the screen
3. Quickly tap settings or any other control

### Other relevant information

Tested on both Chrome on an iPad Pro running iPadOS 16, and a Chromium on a Tesla (unsure what chrome version, but the car is on 2023.6.11 and the vehicle runs Linux)

**Comment by JipFr** [comment]
I think this might be the z-index issue where the video would overlay the UI, at least on Safari; _I think_ it should be fixed in the next release.

**Comment by mrjvs** [comment]
@maxwellward the newest update have had some rendering fixes. Could you please check if the new update has fixed this for you?

**Comment by maxwellward** [comment]
> @maxwellward the newest update have had some rendering fixes. Could you please check if the new update has fixed this for you?

It looks like it still happens in landscape mode, but not portrait mode. And in portrait mode, the play/pause and skip buttons disappear.

**Comment by maxwellward** [comment]
This seems to have now been resolved, so this issue can be closed if not reproducible :)

**Comment by JipFr** [comment]
Works on my iPad as well. I'll close the issue for now, if it pops back up we can re-open.
